--
-- Extraindo dados da tabela `alunos`
--

INSERT INTO `alunos` (`aluno_id`, `nome`, `status`) VALUES
(1, 'Adriel Bueno', 1),
(4, 'Alana Aparecida', 1),
(5, 'Andressa Emilia', 1),
(6, 'Arthur Fumani', 1),
(7, 'Bernardo Oliveira', 1),
(8, 'Caio Lima', 1),
(9, 'Caio Victor', 1),
(10, 'Carla Fernanda', 1),
(11, 'Cristhian da Silva', 1),
(12, 'Eduardo da Silva', 1),
(13, 'Francielly Santos', 1),
(14, 'Geovani de Andrade', 1),
(15, 'Guilherme de Olveira', 1),
(16, 'Guilherme Dias', 1),
(17, 'Guilherme dos Santos', 1),
(18, 'Guilherme Pacheco', 1),
(19, 'Guilherme Palhares', 1),
(20, 'Gustavo Henrique', 1),
(21, 'Gustavo Martins', 1),
(22, 'Hendryl Rodrigues', 1),
(23, 'Henrique da Silva', 1),
(24, 'João Victor', 1),
(25, 'Jozué Wesley', 1),
(26, 'Julia Vitoria', 1),
(27, 'kethelin Vitória', 1),
(28, 'Livia Toledo', 1),
(29, 'Maria Vitoria', 1),
(30, 'Matheus Martins', 1),
(31, 'Matheus Cunha', 1),
(32, 'Milena de Freitas', 1),
(33, 'Nayla Assis', 1),
(34, 'Paulo Vitor', 1),
(35, 'Pedro Andrelino', 1),
(36, 'Pedro Gonçalves', 1),
(37, 'pedro henrique', 1),
(38, 'Raquel Lima', 1),
(39, 'Samuel Santana', 1),
(40, 'Vinicius Passos', 1);
