#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputOption;

$application = new Application('Create PHP Files', '1.0.0');

$application
    ->register('create:controller')
    ->setDescription('Create a new PHP controller')
    ->addArgument('name', InputArgument::REQUIRED, 'Controller name')
    ->setCode(function ($input, $output) {
        $controllerName = $input->getArgument('name');
        $controllerFile = 'app/Controllers/'. $controllerName . '.php';

        $controllerCode = <<<EOD
<?php

class {$controllerName} {
    // controller code here
}
EOD;

        file_put_contents($controllerFile, $controllerCode);

        $output->writeln('Controller created successfully: ' . $controllerFile);
    });

$application
    ->register('create:model')
    ->setDescription('Create a new PHP model')
    ->addArgument('name', InputArgument::REQUIRED, 'Model name')
    ->setCode(function ($input, $output) {
        $modelName = $input->getArgument('name');
        $modelFile = app/'Models/' . $modelName . '.php';

        $modelCode = <<<EOD
<?php

class {$modelName} {
    // model code here
}
EOD;

        file_put_contents($modelFile, $modelCode);

        $output->writeln('Model created successfully: ' . $modelFile);
    });

$application->run();